// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VjezbaCRUD.EF;

namespace VjezbaCRUD.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190525083438_NovaDB")]
    partial class NovaDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VjezbaCRUD.EntityModels.Faktura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum");

                    b.Property<double>("Iznos");

                    b.Property<int>("KId");

                    b.HasKey("Id");

                    b.HasIndex("KId");

                    b.ToTable("Faktura");
                });

            modelBuilder.Entity("VjezbaCRUD.EntityModels.Kupac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Naziv");

                    b.Property<string>("OpstinaPrebivalista");

                    b.Property<int>("PdvBroj");

                    b.HasKey("Id");

                    b.ToTable("Kupac");
                });

            modelBuilder.Entity("VjezbaCRUD.EntityModels.Opstina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Opstina");
                });

            modelBuilder.Entity("VjezbaCRUD.EntityModels.Proizvod", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("VjezbaCRUD.EntityModels.StavkaFakture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("StavkaFakture");
                });

            modelBuilder.Entity("VjezbaCRUD.EntityModels.Faktura", b =>
                {
                    b.HasOne("VjezbaCRUD.EntityModels.Kupac", "Kupac")
                        .WithMany()
                        .HasForeignKey("KId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
